# Site settings ...
uri: domain.com
url: https://domain.com
name: Your name
title: Mangan Jekyll Theme
email: example@domain.com
author: username
keywords: "Your, Keyword, Here"
description: "I am Pengwei from "
social_username: username

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji